In [63]:
#import pandas

In [64]:
#book_data=pandas.read_csv('BX-Book-Ratings.csv')
#print book_data


In [56]:
import numpy as np
npdata=book_data.as_matrix()
data_first_column=npdata[:,[0]]
final_data=data_first_column[9563:]
#print final_data

In [ ]:
'''WE ARE NOT YET USING THE DATA'''

In [58]:
#Original : Original Matrix with entry 0 meaning unfilled entries to be predicted
#UserFeature :  Features of the User 
#BookFeature : Features of the Books
#K : Number of latent Features
#alpha : Learning Rate
#iterations :  Number of iterations for convergence
import numpy as np
def matrix_factor(Original,UserFeature,BookFeature,K,alpha,iterations) :
    for iteration in range(iterations):
        for i in range(len(Original)) :
            for j in range(len(Original[i])) :
                if Original[i][j] > 0 :
                    eij=Original[i][j] - np.dot(UserFeature[i,:],BookFeature[:,j])
                    for k in range(K) :
                        UserFeature[i][k]=UserFeature[i][k]+(2*alpha*BookFeature[k][j]*eij)
                        BookFeature[k][j]=BookFeature[k][j]+(2*alpha*UserFeature[i][k]*eij)
    return np.dot(UserFeature,BookFeature)
    

In [61]:
A=[[5,3,0,0,1],[4,2,1,0,0],[3,0,0,5,2],[0,0,0,2,3],[1,0,0,4,5],[0,0,0,2,3]]
A=np.array(R)
B=np.random.rand(6,4)
C=np.random.rand(4,5)
Result=matrix_factor(A,B,C,4,0.001,5000)
print Result

[[ 5.          3.          4.57443141  1.          3.10763696]
 [ 4.          2.09085135  3.70208396  1.          2.49954071]
 [ 1.          1.          4.52279936  5.          2.95375098]
 [ 1.          0.20359763  3.62313837  4.          2.17036527]
 [ 3.00062293  1.00000001  5.          4.          3.1632631 ]
 [ 1.65842817  1.34784259  2.1394683   1.03669878  1.45538905]]
